app:
  data_dir: data/raw
  ingest_chunk_size: 100000
  batch_mode: records
  batch_size: 100000
  batch_days: 1


mongodb:
  uri: mongodb://root:secret@localhost:27017/admin
  database: web_logs

jdbc:
  url: jdbc:postgresql://localhost:5433/etl_results
  user: etl
  password: secret

pig:
  image: multietl-pig:latest
  script: app/pig/etl.pig

mapreduce:
  image: multietl-mapreduce:latest
  work_dir: results/mapreduce
  dockerfile: app/mapreduce/Dockerfile
  script: /usr/local/bin/run-mapreduce.sh
